### ISSUE TITLE
Unkown file format for specific VSND_C file

### ISSUE THREAD

**Issue by Maikulole** [sedmelluq/lavaplayer#102]
I have a bunch of VSND_C files (Dota2 sounds), the majority gets played without a problem but some files give me errors.  
https://i.imgur.com/eMD8JKE.png - broo_rival_09.vsnd_c  thorws a "Unknown file format." error.    

I'm not sure how to approach this since most of the files get played without a problem.  
Attached is a zip with a working and a failing sound.   
[Sounds.zip](https://github.com/sedmelluq/lavaplayer/files/1822805/Desktop.zip)

**Comment by sedmelluq** [comment]
That file format is not actually supported (probably some custom archive format). It may sometimes work because MP3 detector does not require a valid MP3 frame to start at the beginning of the file or stream, but scans the first 1000 bytes for a frame (to work with MP3 streams which start giving you bytes from a random position, not from the beginning of a frame).

**Comment by Maikulole** [comment]
Ok, that makes sense. They are extracted from the dota 2 game files, the majority is playable but i was just curious why the same format would behave differently.

**Comment by sedmelluq** [comment]
Closing as the mystery is resolved and there is no point to add support for the specific format.
