### ISSUE TITLE
Question: How to encode in Opus Format to a file?

### ISSUE THREAD

**Issue by Moocow9m** [sedmelluq/lavaplayer#104]
I am looking for a way to write AudioTracks to a file so when a user re-request a song(even after a restart of the bot) it can load up a file that has already been encoded to the opus format. How would I go about getting the encoded data?

**Comment by JamieStivala** [comment]
Make a class that only stores the encoded opus file
Implement Serializable
Save as object

On start of program do a for loop and load the files 

(I recommend saving the files name as the URL so that there wouldn't be need for searching)

**Comment by Moocow9m** [comment]
@JamieStivala I think you misunderstood, I do not know how to get the encoded data. Also If possible I would like to put it in a container like .ogg if possible.

**Comment by sedmelluq** [comment]
It is not trivial at the moment, since you either have to store it in a common container format (like .mkv/.webm) or into a custom format, which will be tricky if you want seeking to work. You would have to save the frames you receive from `.provide()` to that file during playback and only consider the final file as a valid cache if it was played from the start to finish.

I have considered having a built-in cache system, but it is not currently a priority.

**Comment by Moocow9m** [comment]
@sedmelluq After a long look at available encoders, I cannot find out how to make a header to make it into a .opus. The file's bytes and output bytes of the `.provide()` method are almost identical except the required header is missing(and a few bytes at the end that are also part of the container), which makes sense as it seems to not be needed to play the audio, but I cant seem to figure out how to recreate this header. Any ideas?

**Comment by Moocow9m** [comment]
@sedmelluq Thanks for the response, I hope to see the built-in cache system becomes a reality.
