### ISSUE TITLE
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format

### ISSUE THREAD

**Issue by CodeBasePW** [sedmelluq/lavaplayer#143]
So for about the past few weeks or so, I've been helping my friend on a Discord bot. My brain is so small I couldn't figure out how to use lavaplayer. It turns out I wasn't doing anything wrong, it wasn't working because of missing classes from the jar I got from maven. So after fixing all of those issues, I finally got an error that helped me, here it is https://pastebin.com/gdzD9YUQ. I looked into it, and it's due to a container not being detected. I have no idea what this means or why it's missing from the YouTube link I used https://www.youtube.com/watch?v=18JQUYgpOlw.

Anyway, this is my testing code https://pastebin.com/XSQKdJQk.

I'm running Windows 10, and JDK 1.8.0_181.
I've been trying to fix this for days so I'll take any help I can get.

**Comment by Devoxin** [comment]
That YouTube video is working for me on Lavaplayer 1.3.10

**Comment by CodeBasePW** [comment]
Thanks for your feedback. Unfortunately this doesn't help me at all. I'm glad you're having a good time but you're input doesn't give me any insight to the issue.

**Comment by Shoganeko** [comment]
LASAGNA

**Comment by Devoxin** [comment]
@CodeBasePW My input may not offer insight but it does at least suggest that your problem is not a Lavaplayer issue.

It is worth mentioning, however, that [the faq does mention something regarding Maven](https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md#nosuchmethoderror-and-noclassdeffounderror). Perhaps it's worth checking?

If you're still having issues you might have better luck [receiving support in the Discord server](https://discord.gg/xuje9gT)

**Comment by sedmelluq** [comment]
Two possible options here:

- `YoutubeAudioSourceManager` was not added.
- You modified the URL in a way which made it not match what YouTube manager expects.
