### ISSUE TITLE
Playing music via YouTube url's stopped working since this morning

### ISSUE THREAD

**Issue by ChrisVDB36** [sedmelluq/lavaplayer#200]
Everything was working fine up until this morning where a user in my discord reported the bot been broken when looking up youtube urls...
Everything still works for other services such as for example: soundcloud

I tried many different things to come to the point where I believe this problem cannot be fixed on my side but has something to do with Lavalink or Lavaplayer trying to load in youtube information and failing to do so. (thats just a guess at this moment, not pointing fingers)

Can you please look into this, I also uploaded my log file with the latest log when I tested it myself.
Thanks in advance

[log.txt](https://github.com/sedmelluq/lavaplayer/files/3447921/log.txt)

**Comment by MCOfficer** [comment]
1.3.19 was released less than a day ago, which fixes a big problem with youtube, apparently. have you tried that?

**Comment by ChrisVDB36** [comment]
> 1.3.19 was released less than a day ago, which fixes a big problem with youtube, apparently. have you tried that?

Hey thanks for your reply, im kinda stuck on this one here, I use Victoria as a wrapper for Lavalink and now I dont know how to fix this or update this, seems like Lavaplayer is inside Victoria and I do not own that thing, I did report the bug over there aswell but he send me here, im still new in all this stuff as i am learning while doing this so could you maybe help me out with more information on how I can fix this please? Or do I need to go back to the guy who made Victoria and ask him to update it? Thanks in advance

**Comment by MCOfficer** [comment]
Oh... seems like you're out of luck, you're at the end of a rather long supply change.

Assuming this that 1.3.19 is the fix you're looking for:
firstly, lavalink has to be updated to support 1.3.19, which it currently doesn't:
https://github.com/Frederikam/Lavalink/blob/1033d3481c70d1552bd66cd0ed5a70b8b4909b62/build.gradle#L54
The update is on the bumpDependancies branch, so they're working on it, but i reckon you're gonna have to wait for their next release.

Then it's on victoria - i'm not sure if they pin their lavalink version, if yes, they need to update to that next version. only then can you update.

**Comment by ChrisVDB36** [comment]
Thanks for your reply both here and on the Victoria github.
I will have to wait then until they fix this, but now I atleast know its not on my side and have some clarification about it.

I will keep an eye out for updates, thanks again and have a nice day

**Comment by Frederikam** [comment]
@MCOfficer  There's a lot to unpack here.

> firstly, lavalink has to be updated to use lavaplayer 1.3.19, which it currently doesn't:
https://github.com/Frederikam/Lavalink/blob/1033d3481c70d1552bd66cd0ed5a70b8b4909b62/build.gradle#L54

1. Lavalink [was updated immediately](https://github.com/Frederikam/Lavalink/commit/3fa205ea5aa534ed537b47c1f47c733d0d85ac13) after 1.3.19 was released. After all, it was me who wrote the fix.
2. Until now, the fix was not on the master branch. I have drafted a formal release: [3.2.1.1](https://github.com/Frederikam/Lavalink/releases/tag/3.2.1.1)

>The update is on the bumpDependancies branch, so they're working on it, but i reckon you're gonna have to wait for their next release.

3. No I'm not. The bump-dependencies branch has not been in use for 3 months. I comitted directly to the dev branch.

>Then it's on victoria - i'm not sure if they pin their lavalink version, if yes, they need to update to that next lavalink version. only then can you update.

4. While some Java clients for Lavalink contains Lavaplayer, Victoria is not one of them. It's a C# library.

@ChrisVDB36 you will want to switch to [3.2.1.1](https://github.com/Frederikam/Lavalink/releases/tag/3.2.1.1)
