### ISSUE TITLE
How to play youtube by video title?

### ISSUE THREAD

**Issue by Hanzanka** [sedmelluq/lavaplayer#508]
This isn't a issue. Could someone more experienced tell me how i can play youtube sounds bu video title, or provide a website that shows how to do that?

**Comment by MCOfficer** [comment]
You can prefix queries with `ytsearch:`, this will make lavaplayer search for this query on youtube. The search results will be loaded as Playlist, so make sure to check your playlists for isSearchResult.

See for example:
https://github.com/sedmelluq/lavaplayer/blob/b0c536098c4f92e6d03b00f19221021f8f50b19b/testbot/src/main/java/com/sedmelluq/discord/lavaplayer/demo/LocalPlayerDemo.java#L28-L30
https://github.com/EndlessSkyCommunity/EndlessSky-Discord-Bot/blob/master/src/main/java/me/mcofficer/james/audio/Audio.java#L77-L88

---

In the future, please ask questions in #lavaplayer on the [JDA Discord](https://discord.gg/0hMr4ce0tIk3pSjp) instead of the issue tracker.

**Comment by Hanzanka** [comment]
It was that easy:D, Thanks!
