### ISSUE TITLE
Support for GLIBC_2.13

### ISSUE THREAD

**Issue by SirYwell** [sedmelluq/lavaplayer#52]
Could you add support for GLIBC_2.13?

**Comment by sedmelluq** [comment]
No, setting up the toolset for compiling against an old Glibc is a pain, especially if you don't want to use an ancient compiler to do it. An alternative would be to statically link it, but that is also a pain due to the amount of 3rd-party libraries that would have to change to do the same. Might look into statically compiling against a different libc implementation at some point but not now.
