### ISSUE TITLE
Bot is not playing music

### ISSUE THREAD

**Issue by boo105** [sedmelluq/lavaplayer#686]
There is problem something that playing music with lavaPlayer

Trackloaded works very well
But There is no sound

In my case I run Bot in Mac OS (M1)

Is Lavaplayer working in Mac OS?

**Comment by Eukon05** [comment]
In the FAQ, it states that Lavaplayer depends on some native libraries for audio encoding/decoding.
Unfortunately, these are not compiled for MacOS on Apple M1 macs, and they probably won't be for a while, since the maintainer of this repo has disappeared.

Here's a link to the FAQ: 
https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md#unsatisfiedlinkerror-8d9389a5

**Comment by boo105** [comment]
Thanks to your reply
