### ISSUE TITLE
NullPointerException with specific youtube track

### ISSUE THREAD

**Issue by Frederikam** [sedmelluq/lavaplayer#80]
A user told me that he was getting a strange exception when playing this track:

https://www.youtube.com/watch?v=Dp8EuP_0gWI4

This is the stacktrace:
```
java.lang.NullPointerException
    com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:205)
    com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrack(YoutubeAudioSourceManager.java:246)
    com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:177)
    com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:121)
    com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:429)
    com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:415)
    com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:219)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
```

I don't know what might have caused it. The lavaplayer version is `1.2.45`. The same error occurs every time. Other YouTube tracks are working fine.

**Comment by ultimate255** [comment]
That video has a copyright restriction that makes it unavailable in certain countries.
I live in the US and I'm not able to play that video.

![image](https://user-images.githubusercontent.com/8908295/34638724-60bf64b2-f297-11e7-98f7-f4a1a01d2151.png)

**Comment by sedmelluq** [comment]
It was actually caused due to two issues:

- The video ID in that URL is not actually correct, but in case of extra characters, YouTube just removes them (redirects). Made LavaPlayer behave the same way.
- In case the video ID was determined to be in incorrect format, it actually caused an NPE instead of triggering `noMatches`. Not really sure if there would be any reason to have different behavior in the case where the ID is too short vs the video does not exist, as the response from YouTube itself is the same in both cases.

Both issues have now been fixed.
